version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Compile
          command: sbt compile
      - run:
          name: Test
          command: sbt test

